//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_UI_Interaction : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Click
        {
            get
            {
                return SteamVR_Actions.uI_Interaction_Click;
            }
        }
        
        public virtual SteamVR_Action_Boolean OpenMenu
        {
            get
            {
                return SteamVR_Actions.uI_Interaction_OpenMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean ShootRay
        {
            get
            {
                return SteamVR_Actions.uI_Interaction_ShootRay;
            }
        }
    }
}
